# Generated by Django 5.2.12 on 2026-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_supportrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
